Rename img metrics normalized
Lightning-AI/metrics pull request #1293
Opened 2022-10-25 20:47 UTC by Borda

## What does this PR do?

addresses https://github.com/Lightning-AI/metrics/pull/1246#discussion_r1004945697

## Before submitting

- [ ] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-10-26 06:37 UTC, SkafteNicki approved these changes

2022-10-26 07:44 UTC, justusschock requested changes
TBH, I'd prefer to keep it the current way. It is not a `True/False` in most of the cases but rather specifies which mechanism to use for normalization. In this context `normalize` as a verb makes more sense to me than an adjective (`normalized`). Also these changes would be breaking for no real reason.

2022-11-09 08:53 UTC, SkafteNicki commented
@Borda is this still needed?

2022-11-09 09:19 UTC, Borda commented
> @Borda is this still needed?

Was just writing the differences and realized that it is not... :otter:

2022-11-09 09:20 UTC, closed without merging