Update regression docs
Lightning-AI/metrics pull request #1410
Opened 2022-12-24 22:52 UTC by reaganjlee

## What does this PR do?

Updates regression docs as a part of #1365 

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

Some notes from standardizing
- log_cosh.py update() had info about a raise, which I wasn't sure should be in another section or left in the method docstring. Left raise info in the method
- tweedle_deviance.py had different(?) shape information for input on 'forward' and 'update'. Typically, I put the input info of 'forward' and 'update' together, as they are the same from the Metric class. However, the forward took in shapes of ``(N,...)`` while 'update' took shapes of ``(N,d)``. I wasn't sure if they were the same, so marked them separately in docstring
- No references mentioned so no commit for that

2022-12-27 11:02 UTC, Borda approved these changes

2023-01-03 07:34 UTC, SkafteNicki requested changes
Just blocking until output info and formatting is also updated, discussed on slack

2023-01-09 07:07 UTC, SkafteNicki approved these changes

2023-01-18 19:12 UTC, stancld approved these changes

2023-01-18 20:21 UTC, merged