Update text docs
Lightning-AI/metrics pull request #1416
Opened 2022-12-27 07:42 UTC by reaganjlee

## What does this PR do?

Fixes Text docs as a part of #1365 

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

# Some Notes

- Squad.py, 
    - There was a code example, which I wasn't sure if we should keep or not. I left it in for now. 
    - I left the method-specific raise within the method docstring
- sacre_bleu.py, Wasn't sure where to put an additional reference that didn't have an in-line citation, left it on the bottom under "additional citations" for now
- Ter.py, references a specific file within a github repo that was already cited as the repo already. Wasn't sure if this was important, left them as two citations just in case 

No shape info, so no commit needed for that

2022-12-27 11:06 UTC, Borda approved these changes

2022-12-27 11:06 UTC, Borda commented on src/torchmetrics/text/bert.py
> +    `recall` and `f1` with corresponding values.
```suggestion
    As output of 'compute' and 'forward' the metric returns a Python dictionary containing the keys ``precision``,
    ``recall`` and ``f1`` with corresponding values.
```

2023-01-03 07:34 UTC, SkafteNicki requested changes
Just blocking until output formatting is also updated, discussed on slack

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/bleu.py
> +        """Compute Precision Scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/cer.py
> +        """Store references/predictions for computing Character Error Rate scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/chrf.py
> +        """Compute Precision Scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/eed.py
> +        """Update ExtendedEditDistance statistics."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/infolm.py
> +        """Update the metric state by a tokenization of ``preds`` and ``target`` sentencens."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/mer.py
> +        """Store references/predictions for computing Match Error Rate scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/perplexity.py
> +        """Compute and store intermediate statistics for Perplexity."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/rouge.py
> +        """Compute rouge scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/sacre_bleu.py
> +        """Compute Precision Scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/squad.py
>          """Compute F1 Score and Exact Match for a collection of predictions and references.
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/ter.py
> +        """Update TER statistics."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/wer.py
> +        """Store references/predictions for computing Word Error Rate scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/wil.py
> +        """Store predictions/references for computing Word Information Lost scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-09 07:24 UTC, SkafteNicki commented on src/torchmetrics/text/wip.py
> +        """Store predictions/references for computing word Information Preserved scores."""
```suggestion
        """Update state with predictions and targets."""
```

2023-01-24 20:06 UTC, SkafteNicki approved these changes

2023-01-25 06:30 UTC, merged