Raise exception for invalid kwargs
Lightning-AI/metrics pull request #1427
Opened 2023-01-04 21:00 UTC by EPronovost

## What does this PR do?

Fixes #1426 

## Before submitting

- [X] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [X] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [] Did you make sure to **update the docs**?
- [X] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2023-01-05 02:19 UTC, Borda approved these changes

2023-01-05 02:19 UTC, Borda commented on src/torchmetrics/metric.py
> +            raise ValueError("Unexpected keyword arguments: " + " ".join(sorted(kwargs)))
```suggestion
            kwargs_ = [f'`{a}`' for a in sorted(kwargs)]
            raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
```

2023-01-05 02:19 UTC, Borda commented on tests/unittests/bases/test_metric.py
> +    with pytest.raises(ValueError, match="Unexpected keyword arguments: bar foo"):
```suggestion
    with pytest.raises(ValueError, match="Unexpected keyword arguments: `bar`, `foo`"):
```

2023-01-05 02:31 UTC, Borda requested changes

2023-01-05 02:31 UTC, Borda commented on src/torchmetrics/metric.py
> +        if kwargs:
ok, this need some adjustment as you can see failing integrations tests :)

2023-01-06 14:29 UTC, SkafteNicki approved these changes
Fixed the integration.
The integration test had the exact problem mentioned in the issue.

2023-01-09 07:37 UTC, Borda approved these changes

2023-01-12 05:34 UTC, merged